# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:prod
          #image: nginx
          ports:
          - containerPort: 80
          imagePullPolicy: Never
          env:
          - name: FLASK_APP
            value: "todo_app/app"
          - name: FLASK_ENV
            value: "production"  
          - name: LOG_LEVEL
            value: INFO
          - name: LOGGLY_TOKEN
            value: "9ab2f74c658a6b92cf6324f2a32db8e0ce50f1c4169499e92ff32e912fbcae14"  
          - name: SECRET_KEY
            value: "secret-key"
          - name: MONGO_CONNECTION_STRING
            value: "mongodb://terracosmosacc:1y7wUK5fy2GQ1GNgjb7C81XSlqUUTBDPF5D3qaMpxejK89WnJeiuR55xj2xW4g7NSGZbii9dcPbeACDbLWBHxA==@terracosmosacc.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@terracosmosacc@"
          - name: MONGO_DATABASE_NAME
            value: "testDb"
          - name: GITHUB_SECRET_ID
            value: "d5e2cb5240afaddde52f136098b834799a9c1eca"
          - name: GITHUB_CLIENT_ID
            value: "1e42a7308890b507de0e"      