# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:prod
          #image: nginx
          ports:
          - containerPort: 80
          imagePullPolicy: Never
          env:
          - name: FLASK_APP
            value: "todo_app/app"
          - name: FLASK_ENV
            value: "debug"  
          - name: LOG_LEVEL
            value: INFO
          - name: LOGGLY_TOKEN
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: loggly_token

                       
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: secretKey

          - name: MONGO_CONNECTION_STRING
            #value: "mongodb://192.168.65.2:27017"
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: mongoConnectionString

          - name: MONGO_DATABASE_NAME
            
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: mongoDatabaseName

          - name: GITHUB_SECRET_ID
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: githubSecret

          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: githubClient       