name: CI
on: [push] 
jobs: 
  build: 
    name: Build and test 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --env-file .env.test todo-app:test
  
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    needs: build
    steps:    
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker build --target prod --tag scottamass/prod:latest .
    - run: docker push scottamass/prod:latest
    - run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: build and push
      env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}} 
      run: | 
          heroku container:login 
          docker tag scottamass/prod:latest registry.heroku.com/devops-todo/web
          docker push registry.heroku.com/devops-todo/web
          heroku container:release web -a devops-todo