name: CI
on: [push] 
jobs: 
  build: 
    name: Build and test 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --env-file .env.test todo-app:test
  
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out the repo
        uses: actions/checkout@v3

    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  